traducao_mercadorias = {
'álcool': 'alcohol',
'bebidas e vasilhames': 'beverages and containers',
'cobre': 'copper',
'ferro gusa': 'pig iron',
'gasolina': 'gasoline',
'manganês': 'manganese',
'máquinas, motores, peças e acessórios': 'machines, engines, parts and accessories',
'minério de ferro': 'iron ore',
'óleo diesel': 'diesel oil',
'adubo orgânico a granel': 'bulk organic fertilizer',
'adubo orgânico acondicionado': 'packaged organic fertilizer',
'calcário corretivo': 'limestone corrector',
'cimento a granel': 'bulk cement',
'cimento acondicionado': 'packaged cement',
'cloreto de potássio': 'potassium chloride',
'contêiner cheio de 40 pés': 'full 40-foot container',
'farelo de soja': 'soybean meal',
'fosfato': 'phosphate',
'grãos - milho': 'grains - corn',
'grãos - trigo': 'grains - wheat',
'óleo vegetal': 'vegetable oil',
'outros - adubos e fertilizantes': 'others - fertilizers',
'soja': 'soybeans',
'ureia': 'urea',
'açúcar': 'sugar',
'amônia': 'ammonia',
'calcário britado': 'crushed limestone',
'calcário siderúrgico': 'steelmaking limestone',
'carvão mineral': 'mineral coal',
'celulose': 'pulp',
'contêiner cheio de 20 pés': 'full 20-foot container',
'contêiner vazio de 20 pés': 'empty 20-foot container',
'contêiner vazio de 40 pés': 'empty 40-foot container',
'coque': 'coke',
'dolomita': 'dolomite',
'dunito': 'dunite',
'escória': 'slag',
'ilmenita': 'ilmenite',
'outras - carga geral não conteinerizada': 'others - non-containerized general cargo',
'pedras em blocos e placas': 'stone blocks and slabs',
'prd. siderúrgicos - fio máquina': 'steel products - wire rod',
'prd. siderúrgicos - outros': 'steel products - others',
'prd. siderúrgicos - placa': 'steel products - slab',
'prd. siderúrgicos - tarugo': 'steel products - billet',
'sucata': 'scrap',
'tijolos e telhas': 'bricks and tiles',
'toretes': 'timber',
'areia': 'sand',
'bauxita': 'bauxite',
'cal': 'lime',
'cromita': 'chromite',
'enxofre': 'sulfur',
'gesso': 'gypsum',
'lab - sulfonato de alquilbenzeno linear': 'lab - linear alkylbenzene sulfonate',
'magnesita': 'magnesite',
'outros - combust, deriv. petro., alcool': 'others - fuels, petroleum derivatives, alcohol',
'prd. siderúrgicos - bobina - bf': 'steel products - coil - bf',
'prd. siderúrgicos - vergalhões': 'steel products - rebar',
'produtos químicos': 'chemicals',
'ladrilhos e azulejos': 'tiles and ceramics',
'alumínio': 'aluminum',
'argila': 'clay',
'clínquer': 'clinker',
'farinha de trigo': 'wheat flour',
'prd. siderúrgicos - bobina - bq': 'steel products - coil - bq',
'prd. siderúrgicos - tubos': 'steel products - tubes',
'sal': 'salt',
'toras de madeira': 'logs',
'veículos': 'vehicles',
'outros - comb e derivado -  perigoso': 'others - fuel and derivative - hazardous',
'papel': 'paper',
'pellets cítricos': 'citrus pellets',
'adubo fert em geral a granel  - perigoso': 'general bulk fertilizer - hazardous',
'grãos - arroz': 'grains - rice',
'grãos - cevada': 'grains - barley',
'outros - extração vegetal e celulose': 'others - plant extraction and cellulose',
'produtos petroquímicos': 'petrochemical products',
'outros - produção agrícola': 'others - agricultural production',
'antracito': 'anthracite',
'dormentes de madeira': 'wooden sleepers',
'algodão': 'cotton',
'grãos - malte': 'grains - malt',
'outros graneis minerais': 'other mineral bulks',
'outros - indústria cimenteira e construção': 'others - cement and construction industry',
'óleo cru': 'crude oil',
'pó de pedra': 'stone dust',
'fosfato - perigoso': 'phosphate - hazardous',
'contêiner cheio de 20 pés - perigoso': 'full 20-foot container - hazardous',
'contêiner cheio de 40 pés - perigoso': 'full 40-foot container - hazardous',
'outras - c geral não contein - perigoso': 'others - general cargo non-containerized - hazardous',
'coque metalúrgico': 'metallurgical coke',
'outros - adubos e fertiliz - perigoso': 'others - fertilizers - hazardous',
'minério de ferro especial - mrs distancia menor 100 km': 'special iron ore - MRS distance under 100 km',
'demais produtos': 'other products',
'minério de ferro sp - mrs destino sp': 'iron ore sp - MRS destination sp',
'pallets de madeira': 'wooden pallets',
'madeira': 'wood',
'produtos químicos - perigoso': 'chemicals - hazardous',
'dormente de concreto': 'concrete sleeper',
'farelo de milho': 'corn meal',
'contêiner vazio 53 pés': 'empty 53-foot container',
'contêiner cheio 53 pés': 'full 53-foot container',
}

tolls_columns = {
    'categoria_eixo':'categoria'
}